services: 
  database:
    image: postgres
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL","pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    env_file: ./api/.env
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./api:/app/
    command: npm run start
    depends_on:
      database:
        condition: service_healthy

  client:
    build: ./client
    restart: always
    command: npm run dev
    ports:
      - 5173:5173

  gateway:
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - client

